"""initial schema

Revision ID: f79ef558e045
Revises:
Create Date: 2026-10-07 02:10:15.503086

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f79ef558e045"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "businesses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("sector", sa.String(length=60), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("years_operating", sa.Integer(), nullable=False),
        sa.Column("employees", sa.Integer(), nullable=False),
        sa.Column("has_cac_registration", sa.Boolean(), nullable=False),
        sa.Column("has_tin", sa.Boolean(), nullable=False),
        sa.Column("has_business_account", sa.Boolean(), nullable=False),
        sa.Column("keeps_written_records", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id"),
    )
    op.create_table(
        "share_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_share_links_business_id"), "share_links", ["business_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column("narration", sa.String(length=300), nullable=False),
        sa.Column("counterparty", sa.String(length=160), nullable=True),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column("direction", sa.Enum("credit", "debit", name="direction"), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "sales",
                "other_income",
                "loan_in",
                "inventory",
                "rent",
                "payroll",
                "utilities",
                "transport",
                "tax",
                "loan_repayment",
                "bank_charges",
                "transfer",
                "other_expense",
                "uncategorised",
                name="category",
            ),
            nullable=False,
        ),
        sa.Column("category_source", sa.String(length=10), nullable=False),
        sa.Column("source", sa.Enum("csv", "manual", name="source"), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "fingerprint", name="uq_txn_business_fingerprint"),
    )
    op.create_index("ix_txn_business_date", "transactions", ["business_id", "txn_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_txn_business_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_share_links_business_id"), table_name="share_links")
    op.drop_table("share_links")
    op.drop_table("businesses")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
